/* automatically generated by rust-bindgen 0.57.0 */

extern "C" {
    #[doc = " Returns an unsigned integer, depicting"]
    #[doc = " the difference between `a` and `b`."]
    #[doc = ""]
    #[doc = " See http://en.wikipedia.org/wiki/Levenshtein_distance"]
    #[doc = " for more information."]
    pub fn levenshtein(
        a: *const ::std::os::raw::c_char,
        b: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_uint;
}
